require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AvaliacaofisicasController do

  # This should return the minimal set of attributes required to create a valid
  # Avaliacaofisica. As you add validations to Avaliacaofisica, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "peso" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AvaliacaofisicasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all avaliacaofisicas as @avaliacaofisicas" do
      avaliacaofisica = Avaliacaofisica.create! valid_attributes
      get :index, {}, valid_session
      assigns(:avaliacaofisicas).should eq([avaliacaofisica])
    end
  end

  describe "GET show" do
    it "assigns the requested avaliacaofisica as @avaliacaofisica" do
      avaliacaofisica = Avaliacaofisica.create! valid_attributes
      get :show, {:id => avaliacaofisica.to_param}, valid_session
      assigns(:avaliacaofisica).should eq(avaliacaofisica)
    end
  end

  describe "GET new" do
    it "assigns a new avaliacaofisica as @avaliacaofisica" do
      get :new, {}, valid_session
      assigns(:avaliacaofisica).should be_a_new(Avaliacaofisica)
    end
  end

  describe "GET edit" do
    it "assigns the requested avaliacaofisica as @avaliacaofisica" do
      avaliacaofisica = Avaliacaofisica.create! valid_attributes
      get :edit, {:id => avaliacaofisica.to_param}, valid_session
      assigns(:avaliacaofisica).should eq(avaliacaofisica)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Avaliacaofisica" do
        expect {
          post :create, {:avaliacaofisica => valid_attributes}, valid_session
        }.to change(Avaliacaofisica, :count).by(1)
      end

      it "assigns a newly created avaliacaofisica as @avaliacaofisica" do
        post :create, {:avaliacaofisica => valid_attributes}, valid_session
        assigns(:avaliacaofisica).should be_a(Avaliacaofisica)
        assigns(:avaliacaofisica).should be_persisted
      end

      it "redirects to the created avaliacaofisica" do
        post :create, {:avaliacaofisica => valid_attributes}, valid_session
        response.should redirect_to(Avaliacaofisica.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved avaliacaofisica as @avaliacaofisica" do
        # Trigger the behavior that occurs when invalid params are submitted
        Avaliacaofisica.any_instance.stub(:save).and_return(false)
        post :create, {:avaliacaofisica => { "peso" => "invalid value" }}, valid_session
        assigns(:avaliacaofisica).should be_a_new(Avaliacaofisica)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Avaliacaofisica.any_instance.stub(:save).and_return(false)
        post :create, {:avaliacaofisica => { "peso" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested avaliacaofisica" do
        avaliacaofisica = Avaliacaofisica.create! valid_attributes
        # Assuming there are no other avaliacaofisicas in the database, this
        # specifies that the Avaliacaofisica created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Avaliacaofisica.any_instance.should_receive(:update).with({ "peso" => "MyString" })
        put :update, {:id => avaliacaofisica.to_param, :avaliacaofisica => { "peso" => "MyString" }}, valid_session
      end

      it "assigns the requested avaliacaofisica as @avaliacaofisica" do
        avaliacaofisica = Avaliacaofisica.create! valid_attributes
        put :update, {:id => avaliacaofisica.to_param, :avaliacaofisica => valid_attributes}, valid_session
        assigns(:avaliacaofisica).should eq(avaliacaofisica)
      end

      it "redirects to the avaliacaofisica" do
        avaliacaofisica = Avaliacaofisica.create! valid_attributes
        put :update, {:id => avaliacaofisica.to_param, :avaliacaofisica => valid_attributes}, valid_session
        response.should redirect_to(avaliacaofisica)
      end
    end

    describe "with invalid params" do
      it "assigns the avaliacaofisica as @avaliacaofisica" do
        avaliacaofisica = Avaliacaofisica.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Avaliacaofisica.any_instance.stub(:save).and_return(false)
        put :update, {:id => avaliacaofisica.to_param, :avaliacaofisica => { "peso" => "invalid value" }}, valid_session
        assigns(:avaliacaofisica).should eq(avaliacaofisica)
      end

      it "re-renders the 'edit' template" do
        avaliacaofisica = Avaliacaofisica.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Avaliacaofisica.any_instance.stub(:save).and_return(false)
        put :update, {:id => avaliacaofisica.to_param, :avaliacaofisica => { "peso" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested avaliacaofisica" do
      avaliacaofisica = Avaliacaofisica.create! valid_attributes
      expect {
        delete :destroy, {:id => avaliacaofisica.to_param}, valid_session
      }.to change(Avaliacaofisica, :count).by(-1)
    end

    it "redirects to the avaliacaofisicas list" do
      avaliacaofisica = Avaliacaofisica.create! valid_attributes
      delete :destroy, {:id => avaliacaofisica.to_param}, valid_session
      response.should redirect_to(avaliacaofisicas_url)
    end
  end

end
