require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HorasController do

  # This should return the minimal set of attributes required to create a valid
  # Hora. As you add validations to Hora, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "horario" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HorasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all horas as @horas" do
      hora = Hora.create! valid_attributes
      get :index, {}, valid_session
      assigns(:horas).should eq([hora])
    end
  end

  describe "GET show" do
    it "assigns the requested hora as @hora" do
      hora = Hora.create! valid_attributes
      get :show, {:id => hora.to_param}, valid_session
      assigns(:hora).should eq(hora)
    end
  end

  describe "GET new" do
    it "assigns a new hora as @hora" do
      get :new, {}, valid_session
      assigns(:hora).should be_a_new(Hora)
    end
  end

  describe "GET edit" do
    it "assigns the requested hora as @hora" do
      hora = Hora.create! valid_attributes
      get :edit, {:id => hora.to_param}, valid_session
      assigns(:hora).should eq(hora)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Hora" do
        expect {
          post :create, {:hora => valid_attributes}, valid_session
        }.to change(Hora, :count).by(1)
      end

      it "assigns a newly created hora as @hora" do
        post :create, {:hora => valid_attributes}, valid_session
        assigns(:hora).should be_a(Hora)
        assigns(:hora).should be_persisted
      end

      it "redirects to the created hora" do
        post :create, {:hora => valid_attributes}, valid_session
        response.should redirect_to(Hora.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hora as @hora" do
        # Trigger the behavior that occurs when invalid params are submitted
        Hora.any_instance.stub(:save).and_return(false)
        post :create, {:hora => { "horario" => "invalid value" }}, valid_session
        assigns(:hora).should be_a_new(Hora)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Hora.any_instance.stub(:save).and_return(false)
        post :create, {:hora => { "horario" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hora" do
        hora = Hora.create! valid_attributes
        # Assuming there are no other horas in the database, this
        # specifies that the Hora created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Hora.any_instance.should_receive(:update).with({ "horario" => "MyString" })
        put :update, {:id => hora.to_param, :hora => { "horario" => "MyString" }}, valid_session
      end

      it "assigns the requested hora as @hora" do
        hora = Hora.create! valid_attributes
        put :update, {:id => hora.to_param, :hora => valid_attributes}, valid_session
        assigns(:hora).should eq(hora)
      end

      it "redirects to the hora" do
        hora = Hora.create! valid_attributes
        put :update, {:id => hora.to_param, :hora => valid_attributes}, valid_session
        response.should redirect_to(hora)
      end
    end

    describe "with invalid params" do
      it "assigns the hora as @hora" do
        hora = Hora.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Hora.any_instance.stub(:save).and_return(false)
        put :update, {:id => hora.to_param, :hora => { "horario" => "invalid value" }}, valid_session
        assigns(:hora).should eq(hora)
      end

      it "re-renders the 'edit' template" do
        hora = Hora.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Hora.any_instance.stub(:save).and_return(false)
        put :update, {:id => hora.to_param, :hora => { "horario" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hora" do
      hora = Hora.create! valid_attributes
      expect {
        delete :destroy, {:id => hora.to_param}, valid_session
      }.to change(Hora, :count).by(-1)
    end

    it "redirects to the horas list" do
      hora = Hora.create! valid_attributes
      delete :destroy, {:id => hora.to_param}, valid_session
      response.should redirect_to(horas_url)
    end
  end

end
