require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ModalidadesController do

  # This should return the minimal set of attributes required to create a valid
  # Modalidade. As you add validations to Modalidade, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nome" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ModalidadesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all modalidades as @modalidades" do
      modalidade = Modalidade.create! valid_attributes
      get :index, {}, valid_session
      assigns(:modalidades).should eq([modalidade])
    end
  end

  describe "GET show" do
    it "assigns the requested modalidade as @modalidade" do
      modalidade = Modalidade.create! valid_attributes
      get :show, {:id => modalidade.to_param}, valid_session
      assigns(:modalidade).should eq(modalidade)
    end
  end

  describe "GET new" do
    it "assigns a new modalidade as @modalidade" do
      get :new, {}, valid_session
      assigns(:modalidade).should be_a_new(Modalidade)
    end
  end

  describe "GET edit" do
    it "assigns the requested modalidade as @modalidade" do
      modalidade = Modalidade.create! valid_attributes
      get :edit, {:id => modalidade.to_param}, valid_session
      assigns(:modalidade).should eq(modalidade)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Modalidade" do
        expect {
          post :create, {:modalidade => valid_attributes}, valid_session
        }.to change(Modalidade, :count).by(1)
      end

      it "assigns a newly created modalidade as @modalidade" do
        post :create, {:modalidade => valid_attributes}, valid_session
        assigns(:modalidade).should be_a(Modalidade)
        assigns(:modalidade).should be_persisted
      end

      it "redirects to the created modalidade" do
        post :create, {:modalidade => valid_attributes}, valid_session
        response.should redirect_to(Modalidade.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved modalidade as @modalidade" do
        # Trigger the behavior that occurs when invalid params are submitted
        Modalidade.any_instance.stub(:save).and_return(false)
        post :create, {:modalidade => { "nome" => "invalid value" }}, valid_session
        assigns(:modalidade).should be_a_new(Modalidade)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Modalidade.any_instance.stub(:save).and_return(false)
        post :create, {:modalidade => { "nome" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested modalidade" do
        modalidade = Modalidade.create! valid_attributes
        # Assuming there are no other modalidades in the database, this
        # specifies that the Modalidade created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Modalidade.any_instance.should_receive(:update).with({ "nome" => "MyString" })
        put :update, {:id => modalidade.to_param, :modalidade => { "nome" => "MyString" }}, valid_session
      end

      it "assigns the requested modalidade as @modalidade" do
        modalidade = Modalidade.create! valid_attributes
        put :update, {:id => modalidade.to_param, :modalidade => valid_attributes}, valid_session
        assigns(:modalidade).should eq(modalidade)
      end

      it "redirects to the modalidade" do
        modalidade = Modalidade.create! valid_attributes
        put :update, {:id => modalidade.to_param, :modalidade => valid_attributes}, valid_session
        response.should redirect_to(modalidade)
      end
    end

    describe "with invalid params" do
      it "assigns the modalidade as @modalidade" do
        modalidade = Modalidade.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Modalidade.any_instance.stub(:save).and_return(false)
        put :update, {:id => modalidade.to_param, :modalidade => { "nome" => "invalid value" }}, valid_session
        assigns(:modalidade).should eq(modalidade)
      end

      it "re-renders the 'edit' template" do
        modalidade = Modalidade.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Modalidade.any_instance.stub(:save).and_return(false)
        put :update, {:id => modalidade.to_param, :modalidade => { "nome" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested modalidade" do
      modalidade = Modalidade.create! valid_attributes
      expect {
        delete :destroy, {:id => modalidade.to_param}, valid_session
      }.to change(Modalidade, :count).by(-1)
    end

    it "redirects to the modalidades list" do
      modalidade = Modalidade.create! valid_attributes
      delete :destroy, {:id => modalidade.to_param}, valid_session
      response.should redirect_to(modalidades_url)
    end
  end

end
